name: food_recipes
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.6.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.12
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/lottie/

  uses-material-design: true
